version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  heroku: circleci/heroku@1.2.4

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run tests
          command: npm run test -- --maxWorkers=2
      - codecov/upload:
          file: ./coverage/coverage-final.json
  "deploy to stage":
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: "dumbbell-admin-stage"
  "deploy to prod":
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: "dumbbell-admin"

workflows:
  version: 2
  workflow:
    jobs:
      - ci
      - "deploy to stage":
          requires:
            - ci
      - "deploy to prod":
          requires:
            - "deploy to stage"