version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run tests
          command: npm run test
      - codecov/upload:
          file: ./coverage/coverage-final.json

workflows:
  version: 2
  workflow:
    jobs:
      - ci
